using System;
using System.Linq;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Amsterfam.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ReplaceEventIdWithGuid : Migration
    {
        private static readonly string[] DependentTables =
        [
            "Accommodations",
            "Activities",
            "AvailabilityEntries",
            "EventAttendances",
            "EventComfortQuestions",
            "ShoppingItems",
            "ItineraryEntries",
            "DatePollEntries",
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Event.Id switches from a sequential int to a Guid so event URLs stop being
            // guessable (see issue #93). This is a destructive migration: it has no
            // meaningful int->uuid value mapping, and the app has no production data yet,
            // so all event-scoped data is wiped rather than backfilled with disconnected
            // random guids that would silently break existing relationships.
            foreach (var table in DependentTables)
                migrationBuilder.DropForeignKey(name: $"FK_{table}_Events_EventId", table: table);

            migrationBuilder.Sql(
                $"""TRUNCATE TABLE {string.Join(", ", DependentTables.Select(t => $"\"{t}\""))}, "Events" RESTART IDENTITY CASCADE;"""
            );

            migrationBuilder.DropPrimaryKey(name: "PK_Events", table: "Events");

            migrationBuilder.Sql(
                """
                ALTER TABLE "Events" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
                ALTER TABLE "Events" ALTER COLUMN "Id" TYPE uuid USING gen_random_uuid();
                """
            );

            migrationBuilder.AddPrimaryKey(name: "PK_Events", table: "Events", column: "Id");

            foreach (var table in DependentTables)
            {
                migrationBuilder.Sql(
                    $"""ALTER TABLE "{table}" ALTER COLUMN "EventId" TYPE uuid USING gen_random_uuid();"""
                );

                migrationBuilder.AddForeignKey(
                    name: $"FK_{table}_Events_EventId",
                    table: table,
                    column: "EventId",
                    principalTable: "Events",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade
                );
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Best-effort only: rolling back regenerates fresh serial ids with no
            // relationship to the guids being discarded. Acceptable since Up() is
            // itself destructive (see comment above) — there is nothing meaningful
            // to restore.
            foreach (var table in DependentTables)
                migrationBuilder.DropForeignKey(name: $"FK_{table}_Events_EventId", table: table);

            migrationBuilder.Sql(
                $"""TRUNCATE TABLE {string.Join(", ", DependentTables.Select(t => $"\"{t}\""))}, "Events" RESTART IDENTITY CASCADE;"""
            );

            migrationBuilder.DropPrimaryKey(name: "PK_Events", table: "Events");

            migrationBuilder.Sql(
                """ALTER TABLE "Events" ALTER COLUMN "Id" TYPE integer USING 0;"""
            );

            migrationBuilder.AddPrimaryKey(name: "PK_Events", table: "Events", column: "Id");

            migrationBuilder.Sql(
                """ALTER TABLE "Events" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;"""
            );

            foreach (var table in DependentTables)
            {
                migrationBuilder.Sql(
                    $"""ALTER TABLE "{table}" ALTER COLUMN "EventId" TYPE integer USING 0;"""
                );

                migrationBuilder.AddForeignKey(
                    name: $"FK_{table}_Events_EventId",
                    table: table,
                    column: "EventId",
                    principalTable: "Events",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade
                );
            }
        }
    }
}
