version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/backend/Amsterfam"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "backend"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
