version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/backend/Amsterfam"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "backend"
    groups:
      aspnetcore:
        patterns:
          - "Microsoft.AspNetCore*"
      entityframework:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
          - "Npgsql.EntityFrameworkCore*"
      testcontainers:
        patterns:
          - "Testcontainers*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
